# Generated by Django 6.1.1 on 2026-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_comment_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="appointment_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="comment",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="kind",
            field=models.CharField(
                choices=[("question", "Question"), ("experience", "Experience")],
                default="question",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="wait_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Days between the appointment and getting the passport back.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=2000),
        ),
    ]
