# Generated by Django 6.1.1 on 2026-10-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_openingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('published_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CountryVisaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('applications', models.PositiveIntegerField()),
                ('issued', models.PositiveIntegerField()),
                ('multiple_entry', models.PositiveIntegerField()),
                ('refused', models.PositiveIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_stats', to='core.statsdataset')),
            ],
            options={
                'ordering': ['country_name'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'country_code'), name='unique_country_stat_per_dataset')],
            },
        ),
        migrations.CreateModel(
            name='ConsulateVisaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('applications', models.PositiveIntegerField()),
                ('refusal_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulate_stats', to='core.statsdataset')),
            ],
            options={
                'ordering': ['-refusal_rate', 'country_name', 'city'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'country_code', 'city'), name='unique_consulate_stat_per_dataset')],
            },
        ),
    ]
